services:
  api:
    build:
      context: .
      dockerfile: TaskService/Api/Dockerfile
    image: tasktracker-api:local
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
